services:
  postgres:
    image: postgres
    restart: always
    volumes:
     - todo-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  hw2:
    build: .
    ports:
      - 3000:3000
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres

volumes:
  todo-postgres-data:
